server:
  port: 8889
  tomcat:
    uri-encoding: UTF-8
    
spring:
  application:
    name: admin-server
    
management:
  security:
    enabled: false
    
eureka:
  healthcheck:
      enabled: true
  client:
    service-url:
      defaultZone: http://user:123456@192.168.1.116:8761/eureka,http://user:123456@192.168.1.116:8762/eureka,http://user:123456@192.168.1.116:8763/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.cleint.ipAddress}