server:
  port: 8761
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: eureka-server
  profiles: server1
  
#权限认证   
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
    
#eureka注册与发现配置  
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123456@localhost:8762/eureka,http://user:123456@localhost:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
    
---
server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: eureka-server
  profiles: server2
  
#权限认证   
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
    
#eureka注册与发现配置  
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka,http://user:123456@localhost:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
    
---
server:
  port: 8763
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: eureka-server
  profiles: server3
  
#权限认证   
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
    
#eureka注册与发现配置  
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka,http://user:123456@localhost:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}